steps:
# Install backend dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'server'

# Install frontend dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'public'

# Set environment variables for React build
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'export REACT_APP_LOCALHOST_USER="GUP-SUP-USER" && npm run build'
  dir: 'public'

# Copy frontend build to backend public directory
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'public/build/*', 'server/public/']

# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mern-app:$COMMIT_SHA', '.']
  dir: '.'

# Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mern-app:$COMMIT_SHA']

images:
- 'gcr.io/$PROJECT_ID/mern-app:$COMMIT_SHA'

# Optional: Set machine type
options:
  machineType: 'N1_HIGHCPU_8'
